config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :songs, except: [:new, :edit] do
      get 'stream', on: :collection
    end
    resources :tags, only: [:show, :index]
    resources :users, only: [:show, :index]
    resources :subscriptions, only: [:create, :destroy]
    resources :listens, only: [:create, :index]
    resources :playlists, only: [:show, :index, :create, :destroy]
    resources :searches, only: :index
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :songs, foreign_key: :uploader_id, counter_cache: true

  has_many :subscribeds, class_name: 'Subscription', foreign_key: :follower_id

  has_many :listens
  has_many :listened_songs, through: :listens, source: :song

  has_many :playlists

  after_initialize :ensure_session_token

  attr_accessor :password

  def self.find_by_credentials(credentials)
    user = self.find_by(username: credentials[:username])
    user if user && user.is_password?(credentials[:password])
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    save
    session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def stream
    song_id_query = <<-SQL
SELECT
  songs.id
FROM
  songs
JOIN
  taggings
ON
  taggings.song_id = songs.id
JOIN
  tags
ON
  taggings.tag_id = tags.id
JOIN
  subscriptions
ON
  subscriptions.subscribable_id = tags.id AND subscriptions.subscribable_type = 'Tag'
WHERE
  subscriptions.follower_id = #{id}
UNION
SELECT
  songs.id
FROM
  songs
JOIN
  subscriptions
ON
  subscriptions.subscribable_id = songs.uploader_id AND
    subscriptions.subscribable_type = 'User'
WHERE
  subscriptions.follower_id = #{id}
SQL
    song_ids = ActiveRecord::Base.connection.execute(song_id_query).map do |h|
      h['id'].to_i
    end

    Song.where('"songs"."id" IN (?)', song_ids)
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def show
      @user = User.includes(songs: [:uploader, :tags]).find(params[:id])
      if !@user
        render json: ['404 user not found'], status: :not_found
      end
    end

    def index
      @users = User.page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_forbidden

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<form class="" action="<%= action %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input
    type="text"
    name="user[username]"
    value="<%= user.username %>"
    placeholder="username">

  <input
    type="password"
    name="user[password]"
    placeholder="password">

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/users/new.html.erb
<div class="top-bar">
  <img src="<%= asset_url('logo.png') %>" />
  <div class="top-bar-gradient"></div>
</div>
<div class="landing-info-panel">
  <h1>SilentIsland is a music discovery and sharing web app, inspired by SoundCloud.</h1>
</div>
<div class="auth-form panel">
  <h1>Sign Up</h1>
  <p>or <a href="<%= new_session_url %>">sign in</a></p>
  <%= render 'shared/errors' %>
  <%= render 'form', user: @user, submit_text: 'Sign Up', action: users_url %>
  <form class="" action="<%= session_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="user[username]" value="guest">
    <input type="hidden" name="user[password]" value="password">
    <input type="submit" value="Guest Login">
  </form>
</div>
<div class="background">
</div>